apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: petclinic
spec:
  template:
    spec:
      containers:
      - name: petclinic
        image: registry.example.com/tanzu/petclinic
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      serviceAccountName: petclinic
---