#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"CustomResourceDefinition"}),expects="2+"
---
#@overlay/remove
#@overlay/match missing_ok=True
status: