#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-privileged
  namespace: projectcontour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmware-system-tmc-psp-privileged
subjects:
- kind: ServiceAccount
  name: envoy
  namespace: projectcontour
---