# See: https://github.com/k14s/vendir/blob/develop/docs/vendir-spec.md
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:

##########
# ingress
##########
- path: k8s/ingress
  contents:
  - path: upstream/contour
    git:
      url: https://github.com/projectcontour/contour
      ref: v1.7.0
    includePaths:
    - examples/contour/**/*
  - path: downstream
    manual: {}
  - path: config
    manual: {}

##########
# kpack
##########
- path: k8s/kpack
  contents:
  - path: upstream/kpack
    githubRelease:
      slug: pivotal/kpack
      tag: v0.0.9
      disableAutoChecksumValidation: true
    includePaths:
    - release-0.0.9.yaml
  - path: downstream
    manual: {}
  - path: config
    manual: {}

##########
# testapp
##########
- path: k8s/testapp
  contents:
  - path: upstream
    manual: {}
  - path: downstream
    manual: {}
  - path: config
    manual: {}

##########
# tekton
##########
- path: k8s/tekton
  contents:
  - path: upstream/pipeline
    githubRelease:
      slug: tektoncd/pipeline
      tag: v0.15.2
      disableAutoChecksumValidation: true
    includePaths:
    - release.yaml
  - path: upstream/triggers
    githubRelease:
      slug: tektoncd/triggers
      tag: v0.7.0
      disableAutoChecksumValidation: true
    includePaths:
    - release.yaml
  - path: upstream/dashboard
    githubRelease:
      slug: tektoncd/dashboard
      tag: v0.8.2
      disableAutoChecksumValidation: true
    includePaths:
    - tekton-dashboard-release.yaml
  - path: downstream
    manual: {}
  - path: config
    manual: {}

##########
# wavefront
##########
- path: k8s/wavefront
  contents:
  - path: upstream/collector
    git:
      url: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
      ref: v1.2.1
    includePaths:
    - deploy/kubernetes/**/*
  - path: upstream/proxy
    git:
      url: https://github.com/wavefrontHQ/wavefront-kubernetes
      ref: master
    includePaths:
    - wavefront-proxy/wavefront.yaml
    - ksm-all-in-one/kube-state.yaml
  - path: downstream
    manual: {}
  - path: config
    manual: {}